export const teamBgColors = {
  "ANA": "#CF4520",
  "BOS": "#000000",
  "BUF": "#003087",
  "CAR": "#010101",
  "CBJ": "#041E42",
  "CGY": "#C8102E",
  "CHI": "#CE1126",
  "COL": "#8A2432",
  "DAL": "#00823E",
  "DET": "#C8102E",
  "EDM": "#00205B",
  "FLA": "#C8102E",
  "LAK": "#000000",
  "MIN": "#0E4431",
  "MTL": "#A6192E",
  "NJD": "#CC0000",
  "NSH": "#FFB81C",
  "NYI": "#00468B",
  "NYR": "#0033A0",
  "OTT": "#C8102E",
  "PHI": "#D24303",
  "PIT": "#000000",
  "SEA": "#001425",
  "SJS": "#00617F",
  "STL": "#003087",
  "TBL": "#FFFFFF",
  "TOR": "#FFFFFF",
  "UTA": "#010101",
  "VAN": "#00205B",
  "VGK": "#333F48",
  "WPG": "#041E42",
  "WSH": "#C8102E"
};

export const teamFgColors = {
  "ANA": "#000000",
  "BOS": "#FDB717",
  "BUF": "#FFB81C",
  "CAR": "#C8102E",
  "CBJ": "#C8102E",
  "CGY": "#F1BE48",
  "CHI": "#FFFFFF",
  "COL": "#FFFFFF",
  "DAL": "#000000",
  "DET": "#FFFFFF",
  "EDM": "#D14520",
  "FLA": "#041E42",
  "LAK": "#A2AAAD",
  "MIN": "#AC1A2E",
  "MTL": "#FFFFFF",
  "NJD": "#000000",
  "NSH": "#041E42",
  "NYI": "#F26924",
  "NYR": "#C8102E",
  "OTT": "#010101",
  "PHI": "#000000",
  "PIT": "#FFB81C",
  "SEA": "#96D8D8",
  "SJS": "#FFFFFF",
  "STL": "#FFB81C",
  "TBL": "#00205B",
  "TOR": "#08167F",
  "UTA": "#6CACE4",
  "VAN": "#046A38",
  "VGK": "#B9975B",
  "WPG": "#A2AAAD",
  "WSH": "#FFFFFF"
};

export const teamShortNames = {
  "ANA": "Ducks",
  "BOS": "Bruins",
  "BUF": "Sabres",
  "CAR": "Canes",
  "CBJ": "Jackets",
  "CGY": "Flames",
  "CHI": "Hawks",
  "COL": "Avs",
  "DAL": "Stars",
  "DET": "Wings",
  "EDM": "Oilers",
  "FLA": "Panthers",
  "LAK": "Kings",
  "MIN": "Wild",
  "MTL": "Habs",
  "NJD": "Devils",
  "NSH": "Preds",
  "NYI": "Isles",
  "NYR": "Rangers",
  "OTT": "Sens",
  "PHI": "Flyers",
  "PIT": "Pens",
  "SEA": "Kraken",
  "SJS": "Sharks",
  "STL": "Blues",
  "TBL": "Bolts",
  "TOR": "Leafs",
  "UTA": "Utah",
  "VAN": "Canucks",
  "VGK": "Knights",
  "WPG": "Jets",
  "WSH": "Caps"
};

export const teamFullNames = {
  "ANA": "Anaheim Ducks",
  "BOS": "Boston Bruins",
  "BUF": "Buffalo Sabres",
  "CAR": "Carolina Hurricanes",
  "CBJ": "Columbus Blue Jackets",
  "CGY": "Calgary Flames",
  "CHI": "Chicago Blackhawks",
  "COL": "Colorado Avalanche",
  "DAL": "Dallas Stars",
  "DET": "Detroit Red Wings",
  "EDM": "Edmonton Oilers",
  "FLA": "Florida Panthers",
  "LAK": "Los Angeles Kings",
  "MIN": "Minnesota Wild",
  "MTL": "Les Canadiens de Montréal",
  "NJD": "New Jersey Devils",
  "NSH": "Nashville Predators",
  "NYI": "New York Islanders",
  "NYR": "New York Rangers",
  "OTT": "Ottawa Senators",
  "PHI": "Philadelphia Flyers",
  "PIT": "Pittsburgh Penguins",
  "SEA": "Seattle Kraken",
  "SJS": "San Jose Sharks",
  "STL": "St. Louis Blues",
  "TBL": "Tampa Bay Lightning",
  "TOR": "Toronto Maple Leafs",
  "UTA": "Utah Hockey Club",
  "VAN": "Vancouver Canucks",
  "VGK": "Vegas Golden Knights",
  "WPG": "Winnipeg Jets",
  "WSH": "Washington Capitals"
};

export const teamAb = ["ANA", "BOS", "BUF", "CAR", "CBJ", "CGY", "CHI", "COL", "DAL", "DET", "EDM", "FLA", "LAK",
"MIN", "MTL", "NJD", "NSH", "NYI", "NYR", "OTT", "PHI", "PIT", "SEA", "SJS", "STL", "TBL", "TOR",
"UTA", "VAN", "VGK", "WPG", "WSH"];